package com.loopline.puzzle.game

/**
 * Powers the in-game Hint button.
 *
 * Given the puzzle's cells and the stroke the player has drawn *so far*, this
 * searches for a way to visit every remaining cell exactly once, continuing
 * on from wherever the player's finger currently is.
 *
 * Deliberately re-solves from the player's actual current position every
 * time, instead of just replaying the fixed walk [LevelGenerator] used to
 * build the level: a shape can have more than one valid solution, and a
 * player's stroke can legitimately diverge from the generator's original
 * walk while still being completable. Re-solving live means a hint is
 * always valid for the board as it actually stands.
 *
 * Approach: backtracking search over the remaining unvisited cells, with a
 * connectivity prune — before stepping into a candidate cell, check whether
 * the cells that would still be unvisited afterwards form a single
 * connected group. If a move would split the remaining area into two
 * separate pockets, there is no way a single continuous stroke can ever
 * reach both of them, so that branch is abandoned immediately rather than
 * explored to a dead end. Candidates are also tried in order of fewest
 * remaining openings first (Warnsdorff's rule), which visits the most
 * constrained, easy-to-strand cells while they're still reachable. Together
 * these keep the search fast for the corridor-like shapes the generator
 * produces, and a node budget below guards against worst-case shapes
 * hanging the UI thread.
 */
object PathSolver {

    private val directions = listOf(-1 to 0, 1 to 0, 0 to -1, 0 to 1)

    /** Safety valve: abandon the search rather than run unbounded. */
    private const val MAX_STEPS_EXPLORED = 150_000

    /**
     * Returns the sequence of cells (not including [pathSoFar]) that
     * completes the stroke, in order - so `result.first()` is the very next
     * cell to hint at - or null if the search couldn't find a completion
     * (either none exists from this exact position, which shouldn't happen
     * for a level generated by [LevelGenerator], or the node budget ran out
     * on an unusually large board).
     */
    fun solveRemaining(allCells: Set<Cell>, pathSoFar: List<Cell>): List<Cell>? {
        if (pathSoFar.isEmpty()) return null
        val remainingTarget = allCells.size - pathSoFar.size
        if (remainingTarget <= 0) return emptyList()

        val visited = pathSoFar.toHashSet()
        val order = mutableListOf<Cell>()
        var stepsExplored = 0

        fun neighborsOf(cell: Cell): List<Cell> = directions.mapNotNull { (dr, dc) ->
            val candidate = Cell(cell.row + dr, cell.col + dc)
            candidate.takeIf { it in allCells }
        }

        fun unvisitedStillConnected(): Boolean {
            val remaining = allCells - visited
            if (remaining.size <= 1) return true
            val seed = remaining.first()
            val seen = mutableSetOf(seed)
            val stack = ArrayDeque<Cell>().apply { add(seed) }
            while (stack.isNotEmpty()) {
                val current = stack.removeLast()
                for (neighbor in neighborsOf(current)) {
                    if (neighbor in remaining && seen.add(neighbor)) {
                        stack.add(neighbor)
                    }
                }
            }
            return seen.size == remaining.size
        }

        fun dfs(current: Cell): Boolean {
            if (order.size == remainingTarget) return true
            stepsExplored += 1
            if (stepsExplored > MAX_STEPS_EXPLORED) return false

            val candidates = neighborsOf(current)
                .filter { it !in visited }
                .sortedBy { candidate -> neighborsOf(candidate).count { it !in visited } }

            for (next in candidates) {
                visited.add(next)
                order.add(next)
                if (unvisitedStillConnected() && dfs(next)) return true
                order.removeAt(order.lastIndex)
                visited.remove(next)
                if (stepsExplored > MAX_STEPS_EXPLORED) return false
            }
            return false
        }

        val solved = dfs(pathSoFar.last())
        return if (solved) order.toList() else null
    }
}
